// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: clients.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClientsServicesClient is the client API for ClientsServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientsServicesClient interface {
	// Countries
	GetCountries(ctx context.Context, in *RequestCountry, opts ...grpc.CallOption) (*ResponseCountries, error)
	CreateCountry(ctx context.Context, in *RequestCountry, opts ...grpc.CallOption) (*ResponseCountries, error)
	UpdateCountry(ctx context.Context, in *RequestCountry, opts ...grpc.CallOption) (*ResponseCountries, error)
	UpdateCountriesDeletionFlags(ctx context.Context, in *RequestCountriesDeletionFlags, opts ...grpc.CallOption) (*ResponseCountries, error)
	// Address types
	GetAddressesTypes(ctx context.Context, in *RequestAddressType, opts ...grpc.CallOption) (*ResponseAddressesTypes, error)
	CreateAddressType(ctx context.Context, in *RequestAddressType, opts ...grpc.CallOption) (*ResponseAddressesTypes, error)
	UpdateAddressType(ctx context.Context, in *RequestAddressType, opts ...grpc.CallOption) (*ResponseAddressesTypes, error)
	UpdateAddressTypeDeletionFlags(ctx context.Context, in *RequestAddressesTypesDeletionFlags, opts ...grpc.CallOption) (*ResponseAddressesTypes, error)
	// Deliveries
	GetDeliveries(ctx context.Context, in *RequestDelivery, opts ...grpc.CallOption) (*ResponseDeliveries, error)
	CreateDelivery(ctx context.Context, in *RequestDelivery, opts ...grpc.CallOption) (*ResponseDeliveries, error)
	UpdateDelivery(ctx context.Context, in *RequestDelivery, opts ...grpc.CallOption) (*ResponseDeliveries, error)
	UpdateDeliveriesDeletionFlags(ctx context.Context, in *RequestDeliveriesDeletionFlags, opts ...grpc.CallOption) (*ResponseDeliveries, error)
	// Notes
	GetNotes(ctx context.Context, in *RequestNote, opts ...grpc.CallOption) (*ResponseNotes, error)
	CreateNote(ctx context.Context, in *RequestNote, opts ...grpc.CallOption) (*ResponseNotes, error)
	UpdateNote(ctx context.Context, in *RequestNote, opts ...grpc.CallOption) (*ResponseNotes, error)
	UpdateNotesDeletionFlags(ctx context.Context, in *RequestNotesDeletionFlags, opts ...grpc.CallOption) (*ResponseNotes, error)
	// Addresses
	GetAddresses(ctx context.Context, in *RequestAddress, opts ...grpc.CallOption) (*ResponseAddresses, error)
	CreateAddress(ctx context.Context, in *RequestAddress, opts ...grpc.CallOption) (*ResponseAddresses, error)
	UpdateAddress(ctx context.Context, in *RequestAddress, opts ...grpc.CallOption) (*ResponseAddresses, error)
	UpdateAddressesDeletionFlags(ctx context.Context, in *RequestAddressesDeletionFlags, opts ...grpc.CallOption) (*ResponseAddresses, error)
	// Clients
	GetClients(ctx context.Context, in *RequestClient, opts ...grpc.CallOption) (*ResponseClients, error)
	CreateClient(ctx context.Context, in *RequestClient, opts ...grpc.CallOption) (*ResponseClients, error)
	UpdateClient(ctx context.Context, in *RequestClient, opts ...grpc.CallOption) (*ResponseClients, error)
	UpdateClientsDeletionFlags(ctx context.Context, in *RequestClientsDeletionFlags, opts ...grpc.CallOption) (*ResponseClients, error)
}

type clientsServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewClientsServicesClient(cc grpc.ClientConnInterface) ClientsServicesClient {
	return &clientsServicesClient{cc}
}

func (c *clientsServicesClient) GetCountries(ctx context.Context, in *RequestCountry, opts ...grpc.CallOption) (*ResponseCountries, error) {
	out := new(ResponseCountries)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/GetCountries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) CreateCountry(ctx context.Context, in *RequestCountry, opts ...grpc.CallOption) (*ResponseCountries, error) {
	out := new(ResponseCountries)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/CreateCountry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) UpdateCountry(ctx context.Context, in *RequestCountry, opts ...grpc.CallOption) (*ResponseCountries, error) {
	out := new(ResponseCountries)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/UpdateCountry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) UpdateCountriesDeletionFlags(ctx context.Context, in *RequestCountriesDeletionFlags, opts ...grpc.CallOption) (*ResponseCountries, error) {
	out := new(ResponseCountries)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/UpdateCountriesDeletionFlags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) GetAddressesTypes(ctx context.Context, in *RequestAddressType, opts ...grpc.CallOption) (*ResponseAddressesTypes, error) {
	out := new(ResponseAddressesTypes)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/GetAddressesTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) CreateAddressType(ctx context.Context, in *RequestAddressType, opts ...grpc.CallOption) (*ResponseAddressesTypes, error) {
	out := new(ResponseAddressesTypes)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/CreateAddressType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) UpdateAddressType(ctx context.Context, in *RequestAddressType, opts ...grpc.CallOption) (*ResponseAddressesTypes, error) {
	out := new(ResponseAddressesTypes)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/UpdateAddressType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) UpdateAddressTypeDeletionFlags(ctx context.Context, in *RequestAddressesTypesDeletionFlags, opts ...grpc.CallOption) (*ResponseAddressesTypes, error) {
	out := new(ResponseAddressesTypes)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/UpdateAddressTypeDeletionFlags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) GetDeliveries(ctx context.Context, in *RequestDelivery, opts ...grpc.CallOption) (*ResponseDeliveries, error) {
	out := new(ResponseDeliveries)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/GetDeliveries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) CreateDelivery(ctx context.Context, in *RequestDelivery, opts ...grpc.CallOption) (*ResponseDeliveries, error) {
	out := new(ResponseDeliveries)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/CreateDelivery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) UpdateDelivery(ctx context.Context, in *RequestDelivery, opts ...grpc.CallOption) (*ResponseDeliveries, error) {
	out := new(ResponseDeliveries)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/UpdateDelivery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) UpdateDeliveriesDeletionFlags(ctx context.Context, in *RequestDeliveriesDeletionFlags, opts ...grpc.CallOption) (*ResponseDeliveries, error) {
	out := new(ResponseDeliveries)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/UpdateDeliveriesDeletionFlags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) GetNotes(ctx context.Context, in *RequestNote, opts ...grpc.CallOption) (*ResponseNotes, error) {
	out := new(ResponseNotes)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/GetNotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) CreateNote(ctx context.Context, in *RequestNote, opts ...grpc.CallOption) (*ResponseNotes, error) {
	out := new(ResponseNotes)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/CreateNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) UpdateNote(ctx context.Context, in *RequestNote, opts ...grpc.CallOption) (*ResponseNotes, error) {
	out := new(ResponseNotes)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/UpdateNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) UpdateNotesDeletionFlags(ctx context.Context, in *RequestNotesDeletionFlags, opts ...grpc.CallOption) (*ResponseNotes, error) {
	out := new(ResponseNotes)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/UpdateNotesDeletionFlags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) GetAddresses(ctx context.Context, in *RequestAddress, opts ...grpc.CallOption) (*ResponseAddresses, error) {
	out := new(ResponseAddresses)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/GetAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) CreateAddress(ctx context.Context, in *RequestAddress, opts ...grpc.CallOption) (*ResponseAddresses, error) {
	out := new(ResponseAddresses)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/CreateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) UpdateAddress(ctx context.Context, in *RequestAddress, opts ...grpc.CallOption) (*ResponseAddresses, error) {
	out := new(ResponseAddresses)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/UpdateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) UpdateAddressesDeletionFlags(ctx context.Context, in *RequestAddressesDeletionFlags, opts ...grpc.CallOption) (*ResponseAddresses, error) {
	out := new(ResponseAddresses)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/UpdateAddressesDeletionFlags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) GetClients(ctx context.Context, in *RequestClient, opts ...grpc.CallOption) (*ResponseClients, error) {
	out := new(ResponseClients)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/GetClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) CreateClient(ctx context.Context, in *RequestClient, opts ...grpc.CallOption) (*ResponseClients, error) {
	out := new(ResponseClients)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/CreateClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) UpdateClient(ctx context.Context, in *RequestClient, opts ...grpc.CallOption) (*ResponseClients, error) {
	out := new(ResponseClients)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/UpdateClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServicesClient) UpdateClientsDeletionFlags(ctx context.Context, in *RequestClientsDeletionFlags, opts ...grpc.CallOption) (*ResponseClients, error) {
	out := new(ResponseClients)
	err := c.cc.Invoke(ctx, "/clients.ClientsServices/UpdateClientsDeletionFlags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientsServicesServer is the server API for ClientsServices service.
// All implementations must embed UnimplementedClientsServicesServer
// for forward compatibility
type ClientsServicesServer interface {
	// Countries
	GetCountries(context.Context, *RequestCountry) (*ResponseCountries, error)
	CreateCountry(context.Context, *RequestCountry) (*ResponseCountries, error)
	UpdateCountry(context.Context, *RequestCountry) (*ResponseCountries, error)
	UpdateCountriesDeletionFlags(context.Context, *RequestCountriesDeletionFlags) (*ResponseCountries, error)
	// Address types
	GetAddressesTypes(context.Context, *RequestAddressType) (*ResponseAddressesTypes, error)
	CreateAddressType(context.Context, *RequestAddressType) (*ResponseAddressesTypes, error)
	UpdateAddressType(context.Context, *RequestAddressType) (*ResponseAddressesTypes, error)
	UpdateAddressTypeDeletionFlags(context.Context, *RequestAddressesTypesDeletionFlags) (*ResponseAddressesTypes, error)
	// Deliveries
	GetDeliveries(context.Context, *RequestDelivery) (*ResponseDeliveries, error)
	CreateDelivery(context.Context, *RequestDelivery) (*ResponseDeliveries, error)
	UpdateDelivery(context.Context, *RequestDelivery) (*ResponseDeliveries, error)
	UpdateDeliveriesDeletionFlags(context.Context, *RequestDeliveriesDeletionFlags) (*ResponseDeliveries, error)
	// Notes
	GetNotes(context.Context, *RequestNote) (*ResponseNotes, error)
	CreateNote(context.Context, *RequestNote) (*ResponseNotes, error)
	UpdateNote(context.Context, *RequestNote) (*ResponseNotes, error)
	UpdateNotesDeletionFlags(context.Context, *RequestNotesDeletionFlags) (*ResponseNotes, error)
	// Addresses
	GetAddresses(context.Context, *RequestAddress) (*ResponseAddresses, error)
	CreateAddress(context.Context, *RequestAddress) (*ResponseAddresses, error)
	UpdateAddress(context.Context, *RequestAddress) (*ResponseAddresses, error)
	UpdateAddressesDeletionFlags(context.Context, *RequestAddressesDeletionFlags) (*ResponseAddresses, error)
	// Clients
	GetClients(context.Context, *RequestClient) (*ResponseClients, error)
	CreateClient(context.Context, *RequestClient) (*ResponseClients, error)
	UpdateClient(context.Context, *RequestClient) (*ResponseClients, error)
	UpdateClientsDeletionFlags(context.Context, *RequestClientsDeletionFlags) (*ResponseClients, error)
	mustEmbedUnimplementedClientsServicesServer()
}

// UnimplementedClientsServicesServer must be embedded to have forward compatible implementations.
type UnimplementedClientsServicesServer struct {
}

func (UnimplementedClientsServicesServer) GetCountries(context.Context, *RequestCountry) (*ResponseCountries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountries not implemented")
}
func (UnimplementedClientsServicesServer) CreateCountry(context.Context, *RequestCountry) (*ResponseCountries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCountry not implemented")
}
func (UnimplementedClientsServicesServer) UpdateCountry(context.Context, *RequestCountry) (*ResponseCountries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCountry not implemented")
}
func (UnimplementedClientsServicesServer) UpdateCountriesDeletionFlags(context.Context, *RequestCountriesDeletionFlags) (*ResponseCountries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCountriesDeletionFlags not implemented")
}
func (UnimplementedClientsServicesServer) GetAddressesTypes(context.Context, *RequestAddressType) (*ResponseAddressesTypes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressesTypes not implemented")
}
func (UnimplementedClientsServicesServer) CreateAddressType(context.Context, *RequestAddressType) (*ResponseAddressesTypes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAddressType not implemented")
}
func (UnimplementedClientsServicesServer) UpdateAddressType(context.Context, *RequestAddressType) (*ResponseAddressesTypes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAddressType not implemented")
}
func (UnimplementedClientsServicesServer) UpdateAddressTypeDeletionFlags(context.Context, *RequestAddressesTypesDeletionFlags) (*ResponseAddressesTypes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAddressTypeDeletionFlags not implemented")
}
func (UnimplementedClientsServicesServer) GetDeliveries(context.Context, *RequestDelivery) (*ResponseDeliveries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeliveries not implemented")
}
func (UnimplementedClientsServicesServer) CreateDelivery(context.Context, *RequestDelivery) (*ResponseDeliveries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDelivery not implemented")
}
func (UnimplementedClientsServicesServer) UpdateDelivery(context.Context, *RequestDelivery) (*ResponseDeliveries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDelivery not implemented")
}
func (UnimplementedClientsServicesServer) UpdateDeliveriesDeletionFlags(context.Context, *RequestDeliveriesDeletionFlags) (*ResponseDeliveries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeliveriesDeletionFlags not implemented")
}
func (UnimplementedClientsServicesServer) GetNotes(context.Context, *RequestNote) (*ResponseNotes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotes not implemented")
}
func (UnimplementedClientsServicesServer) CreateNote(context.Context, *RequestNote) (*ResponseNotes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNote not implemented")
}
func (UnimplementedClientsServicesServer) UpdateNote(context.Context, *RequestNote) (*ResponseNotes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNote not implemented")
}
func (UnimplementedClientsServicesServer) UpdateNotesDeletionFlags(context.Context, *RequestNotesDeletionFlags) (*ResponseNotes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNotesDeletionFlags not implemented")
}
func (UnimplementedClientsServicesServer) GetAddresses(context.Context, *RequestAddress) (*ResponseAddresses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddresses not implemented")
}
func (UnimplementedClientsServicesServer) CreateAddress(context.Context, *RequestAddress) (*ResponseAddresses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAddress not implemented")
}
func (UnimplementedClientsServicesServer) UpdateAddress(context.Context, *RequestAddress) (*ResponseAddresses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAddress not implemented")
}
func (UnimplementedClientsServicesServer) UpdateAddressesDeletionFlags(context.Context, *RequestAddressesDeletionFlags) (*ResponseAddresses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAddressesDeletionFlags not implemented")
}
func (UnimplementedClientsServicesServer) GetClients(context.Context, *RequestClient) (*ResponseClients, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClients not implemented")
}
func (UnimplementedClientsServicesServer) CreateClient(context.Context, *RequestClient) (*ResponseClients, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClient not implemented")
}
func (UnimplementedClientsServicesServer) UpdateClient(context.Context, *RequestClient) (*ResponseClients, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClient not implemented")
}
func (UnimplementedClientsServicesServer) UpdateClientsDeletionFlags(context.Context, *RequestClientsDeletionFlags) (*ResponseClients, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClientsDeletionFlags not implemented")
}
func (UnimplementedClientsServicesServer) mustEmbedUnimplementedClientsServicesServer() {}

// UnsafeClientsServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientsServicesServer will
// result in compilation errors.
type UnsafeClientsServicesServer interface {
	mustEmbedUnimplementedClientsServicesServer()
}

func RegisterClientsServicesServer(s grpc.ServiceRegistrar, srv ClientsServicesServer) {
	s.RegisterService(&ClientsServices_ServiceDesc, srv)
}

func _ClientsServices_GetCountries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCountry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).GetCountries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/GetCountries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).GetCountries(ctx, req.(*RequestCountry))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_CreateCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCountry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).CreateCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/CreateCountry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).CreateCountry(ctx, req.(*RequestCountry))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_UpdateCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCountry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).UpdateCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/UpdateCountry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).UpdateCountry(ctx, req.(*RequestCountry))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_UpdateCountriesDeletionFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCountriesDeletionFlags)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).UpdateCountriesDeletionFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/UpdateCountriesDeletionFlags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).UpdateCountriesDeletionFlags(ctx, req.(*RequestCountriesDeletionFlags))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_GetAddressesTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAddressType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).GetAddressesTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/GetAddressesTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).GetAddressesTypes(ctx, req.(*RequestAddressType))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_CreateAddressType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAddressType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).CreateAddressType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/CreateAddressType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).CreateAddressType(ctx, req.(*RequestAddressType))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_UpdateAddressType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAddressType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).UpdateAddressType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/UpdateAddressType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).UpdateAddressType(ctx, req.(*RequestAddressType))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_UpdateAddressTypeDeletionFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAddressesTypesDeletionFlags)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).UpdateAddressTypeDeletionFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/UpdateAddressTypeDeletionFlags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).UpdateAddressTypeDeletionFlags(ctx, req.(*RequestAddressesTypesDeletionFlags))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_GetDeliveries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDelivery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).GetDeliveries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/GetDeliveries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).GetDeliveries(ctx, req.(*RequestDelivery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_CreateDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDelivery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).CreateDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/CreateDelivery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).CreateDelivery(ctx, req.(*RequestDelivery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_UpdateDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDelivery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).UpdateDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/UpdateDelivery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).UpdateDelivery(ctx, req.(*RequestDelivery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_UpdateDeliveriesDeletionFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDeliveriesDeletionFlags)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).UpdateDeliveriesDeletionFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/UpdateDeliveriesDeletionFlags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).UpdateDeliveriesDeletionFlags(ctx, req.(*RequestDeliveriesDeletionFlags))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_GetNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestNote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).GetNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/GetNotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).GetNotes(ctx, req.(*RequestNote))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestNote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/CreateNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).CreateNote(ctx, req.(*RequestNote))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_UpdateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestNote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).UpdateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/UpdateNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).UpdateNote(ctx, req.(*RequestNote))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_UpdateNotesDeletionFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestNotesDeletionFlags)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).UpdateNotesDeletionFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/UpdateNotesDeletionFlags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).UpdateNotesDeletionFlags(ctx, req.(*RequestNotesDeletionFlags))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_GetAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).GetAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/GetAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).GetAddresses(ctx, req.(*RequestAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_CreateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).CreateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/CreateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).CreateAddress(ctx, req.(*RequestAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_UpdateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).UpdateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/UpdateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).UpdateAddress(ctx, req.(*RequestAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_UpdateAddressesDeletionFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAddressesDeletionFlags)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).UpdateAddressesDeletionFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/UpdateAddressesDeletionFlags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).UpdateAddressesDeletionFlags(ctx, req.(*RequestAddressesDeletionFlags))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_GetClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestClient)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).GetClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/GetClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).GetClients(ctx, req.(*RequestClient))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestClient)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/CreateClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).CreateClient(ctx, req.(*RequestClient))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_UpdateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestClient)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).UpdateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/UpdateClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).UpdateClient(ctx, req.(*RequestClient))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsServices_UpdateClientsDeletionFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestClientsDeletionFlags)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServicesServer).UpdateClientsDeletionFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clients.ClientsServices/UpdateClientsDeletionFlags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServicesServer).UpdateClientsDeletionFlags(ctx, req.(*RequestClientsDeletionFlags))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientsServices_ServiceDesc is the grpc.ServiceDesc for ClientsServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientsServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clients.ClientsServices",
	HandlerType: (*ClientsServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCountries",
			Handler:    _ClientsServices_GetCountries_Handler,
		},
		{
			MethodName: "CreateCountry",
			Handler:    _ClientsServices_CreateCountry_Handler,
		},
		{
			MethodName: "UpdateCountry",
			Handler:    _ClientsServices_UpdateCountry_Handler,
		},
		{
			MethodName: "UpdateCountriesDeletionFlags",
			Handler:    _ClientsServices_UpdateCountriesDeletionFlags_Handler,
		},
		{
			MethodName: "GetAddressesTypes",
			Handler:    _ClientsServices_GetAddressesTypes_Handler,
		},
		{
			MethodName: "CreateAddressType",
			Handler:    _ClientsServices_CreateAddressType_Handler,
		},
		{
			MethodName: "UpdateAddressType",
			Handler:    _ClientsServices_UpdateAddressType_Handler,
		},
		{
			MethodName: "UpdateAddressTypeDeletionFlags",
			Handler:    _ClientsServices_UpdateAddressTypeDeletionFlags_Handler,
		},
		{
			MethodName: "GetDeliveries",
			Handler:    _ClientsServices_GetDeliveries_Handler,
		},
		{
			MethodName: "CreateDelivery",
			Handler:    _ClientsServices_CreateDelivery_Handler,
		},
		{
			MethodName: "UpdateDelivery",
			Handler:    _ClientsServices_UpdateDelivery_Handler,
		},
		{
			MethodName: "UpdateDeliveriesDeletionFlags",
			Handler:    _ClientsServices_UpdateDeliveriesDeletionFlags_Handler,
		},
		{
			MethodName: "GetNotes",
			Handler:    _ClientsServices_GetNotes_Handler,
		},
		{
			MethodName: "CreateNote",
			Handler:    _ClientsServices_CreateNote_Handler,
		},
		{
			MethodName: "UpdateNote",
			Handler:    _ClientsServices_UpdateNote_Handler,
		},
		{
			MethodName: "UpdateNotesDeletionFlags",
			Handler:    _ClientsServices_UpdateNotesDeletionFlags_Handler,
		},
		{
			MethodName: "GetAddresses",
			Handler:    _ClientsServices_GetAddresses_Handler,
		},
		{
			MethodName: "CreateAddress",
			Handler:    _ClientsServices_CreateAddress_Handler,
		},
		{
			MethodName: "UpdateAddress",
			Handler:    _ClientsServices_UpdateAddress_Handler,
		},
		{
			MethodName: "UpdateAddressesDeletionFlags",
			Handler:    _ClientsServices_UpdateAddressesDeletionFlags_Handler,
		},
		{
			MethodName: "GetClients",
			Handler:    _ClientsServices_GetClients_Handler,
		},
		{
			MethodName: "CreateClient",
			Handler:    _ClientsServices_CreateClient_Handler,
		},
		{
			MethodName: "UpdateClient",
			Handler:    _ClientsServices_UpdateClient_Handler,
		},
		{
			MethodName: "UpdateClientsDeletionFlags",
			Handler:    _ClientsServices_UpdateClientsDeletionFlags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clients.proto",
}
